name: End-to-end tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Instala dependências e executa os testes
      - name: Cypress run
        uses: cypress-io/github-action@v5

      # Upload de screenshots (somente em caso de falha)
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Upload de vídeos
      - name: Upload videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
