# .github/workflows/e2e.yml
name: End-to-end tests

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Wait for hosted app
        run: npx wait-on https://conectalutas.netlify.app

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: false
          start: ""
          config: baseUrl=https://conectalutas.netlify.app
